#!/bin/sh
export ARM_CLIENT_ID="$PLUGIN_ARM_CLIENT_ID"
export ARM_CLIENT_SECRET="$PLUGIN_ARM_CLIENT_SECRET"
export ARM_SUBSCRIPTION_ID="$PLUGIN_ARM_SUBSCRIPTION_ID"
export ARM_TENANT_ID="$PLUGIN_ARM_TENANT_ID"
export ARM_ACCESS_KEY=$PLUGIN_ARM_TFSTATE_ACCESS_KEY
export TF_IN_AUTOMATION=true
